### ISSUE TITLE
Access to public site returns an error

### ISSUE THREAD

**Issue by ManOnDaMoon** [ManOnDaMoon/omeka-s-module-RestrictedSites#4]
On access to a standard public site, there is an error message:
```
Error
Call to a member function getMessage() on null

Détails :

Error: Call to a member function getMessage() on null in /Users/laurent/Documents/Collection/dev-omeka-s/application/view/error/index.phtml:6
Stack trace:
#0 /Users/laurent/Documents/Collection/dev-omeka-s/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(506): include()
#1 /Users/laurent/Documents/Collection/dev-omeka-s/vendor/zendframework/zend-view/src/View.php(207): Zend\View\Renderer\PhpRenderer->render(NULL)
#2 /Users/laurent/Documents/Collection/dev-omeka-s/vendor/zendframework/zend-view/src/View.php(236): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#3 /Users/laurent/Documents/Collection/dev-omeka-s/vendor/zendframework/zend-view/src/View.php(200): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#4 /Users/laurent/Documents/Collection/dev-omeka-s/vendor/zendframework/zend-mvc/src/View/Http/DefaultRenderingStrategy.php(105): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#5 /Users/laurent/Documents/Collection/dev-omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
#6 /Users/laurent/Documents/Collection/dev-omeka-s/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent))
#7 /Users/laurent/Documents/Collection/dev-omeka-s/vendor/zendframework/zend-mvc/src/Application.php(367): Zend\EventManager\EventManager->triggerEvent(Object(Zend\Mvc\MvcEvent))
#8 /Users/laurent/Documents/Collection/dev-omeka-s/vendor/zendframework/zend-mvc/src/Application.php(326): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#9 /Users/laurent/Documents/Collection/dev-omeka-s/index.php(21): Zend\Mvc\Application->run()
#10 {main}
```

**Comment by ManOnDaMoon** [comment]
Probably linked to Omeka S alpha

**Comment by ManOnDaMoon** [comment]
Issue fixed in omeka-s
